// Regenerates src/icons/data.ts with only the lucide icons the app actually uses,
// so icons resolve offline without bundling the whole collection.
// Usage: node scripts/gen-icons.mjs
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const used = new Set();
for (const file of walk(join(root, 'src'))) {
  if (!/\.(ts|tsx)$/.test(file)) continue;
  for (const m of readFileSync(file, 'utf8').matchAll(/["']lucide:([a-z0-9-]+)["']/g)) {
    used.add(m[1]);
  }
}

const collection = JSON.parse(
  readFileSync(join(root, 'node_modules/@iconify-json/lucide/icons.json'), 'utf8'),
);

const resolve = (name, seen = new Set()) => {
  if (seen.has(name)) return null;
  seen.add(name);
  if (collection.icons[name]) return collection.icons[name];
  const alias = collection.aliases?.[name];
  return alias ? resolve(alias.parent, seen) : null;
};

const out = {};
const missing = [];
for (const name of [...used].sort()) {
  const icon = resolve(name);
  if (icon) out[name] = icon;
  else missing.push(name);
}
if (missing.length) throw new Error(`Unknown lucide icons: ${missing.join(', ')}`);

writeFileSync(
  join(root, 'src/icons/data.ts'),
  `// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import type { IconifyJSON } from '@iconify/react';

export const lucideSubset: IconifyJSON = ${JSON.stringify(
    { prefix: 'lucide', width: collection.width, height: collection.height, icons: out },
    null,
    2,
  )};
`,
);

console.log(`Wrote ${Object.keys(out).length} icons to src/icons/data.ts`);
